### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by luciostuder** [raulbeijinho/raulbeijinho.github.io#1]
- no index.html insira a lista de laboratorios antes da imagem diw.svg
- falta o lab 2! termine amanhã sem falta!!

**Comment by raulbeijinho** [comment]
como assim stor? que lista de laboratorios?

**Comment by luciostuder** [comment]
os meus laboratorios:

   - lab 1: conhecer a Internet
   - lab 2: a minha cidade

**Comment by raulbeijinho** [comment]
okay, entretanto acho que já terminei o lab2 :)

**Comment by raulbeijinho** [comment]
outra coisa, nos enunciados não tinha este passo, mas não é suposto ter um link no lab1 e no lab2 que regresse a página principal?

e já agora, eu o lab2 fiz sobre a minha freguesia onde moro, não é uma cidade.
